kv_cache_config:
  enable_block_reuse: false
  mamba_ssm_cache_dtype: float16
moe_config:
   backend: CUTLASS
cuda_graph_config:
    enable_padding: true
#    batch_sizes: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
#transforms:
 # visualize_namespace:
  #  enabled: true
